services:

  techclient-db:
    env_file:
      - ../../.env
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: techclient-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      SA_PASSWORD: ${DB_PASSWORD}
    volumes:
      - techclient-db-data:/var/opt/mssql
    networks:
      - techclient-network
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${DB_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  techclient-api:
    env_file:
      - ../../.env
    build:
      context: ../../
      dockerfile: backend/TechClient.API/Dockerfile
    container_name: techclient-api
    secrets:
      - dialogflow_json
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=techclient-db;Database=${DB_NAME};User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;"
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/dialogflow_json
    ports:
      - "5000:8080"
    depends_on:
      techclient-db:
        condition: service_healthy
    networks:
      - techclient-network
    restart: unless-stopped

  techclient-web:
    build:
      context: ../../frontend/techclient-web
      dockerfile: Dockerfile
    container_name: techclient-web
    ports:
      - "4200:80"
    depends_on:
      - techclient-api
    networks:
      - techclient-network
    restart: unless-stopped

volumes:
  techclient-db-data:

networks:
  techclient-network:
    driver: bridge

secrets:
  dialogflow_json:
    file: ../../backend/TechClient.API/credentials/techclient-dialogflow.json