# Stage 1: build
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .
RUN npm run build -- --configuration production

# Stage 2: runtime
FROM nginx:alpine AS runtime

COPY --from=build /app/dist/techclient-web/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80