server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Necessário para o Angular Router funcionar com refresh
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache de assets estáticos
    location ~* \.(js|css|png|jpg|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}